name: Deploy Backend to AWS EC2

on:
  push:
    branches:
      - main # Runs on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_URI }}

      - name: Build and Push Backend Docker Image
        run: |
          docker build -t todo-backend .
          docker tag todo-backend ${{ secrets.AWS_ECR_URI }}/todo-backend:latest
          docker push ${{ secrets.AWS_ECR_URI }}/todo-backend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # ✅ Install Docker if not installed
            if ! command -v docker &> /dev/null
            then
                echo "Docker not found! Installing Docker..."
                sudo apt update -y
                sudo apt install -y docker.io
                sudo systemctl start docker
                sudo systemctl enable docker
                sudo usermod -aG docker $USER
            else
                echo "Docker is already installed."
            fi

            # ✅ Pull and Run Docker Container
            sudo docker stop todo-backend || true
            sudo docker rm todo-backend || true
            sudo docker pull ${{ secrets.AWS_ECR_URI }}/todo-backend:latest
            sudo docker run -d -p 5000:5000 --name todo-backend ${{ secrets.AWS_ECR_URI }}/todo-backend:latest
