name: Deploy Backend to AWS EC2

on:
  push:
    branches:
      - main # Runs on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to AWS ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_URI }}

      - name: Build and Push Backend Docker Image
        run: |
          docker build -t todo-backend .
          docker tag todo-backend ${{ secrets.AWS_ECR_URI }}/todo-backend:latest
          docker push ${{ secrets.AWS_ECR_URI }}/todo-backend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user # Change to ec2-user if using Amazon Linux
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Set AWS credentials inside EC2
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws configure set region us-east-1

            # Login to AWS ECR
            aws ecr get-login-password --region us-east-1 | sudo docker login --username AWS --password-stdin ${{ secrets.AWS_ECR_URI }}

            # Stop and remove existing container (ignore errors if not found)
            sudo docker stop todo-backend || true
            sudo docker rm todo-backend || true

            # Pull the latest Docker image
            sudo docker pull ${{ secrets.AWS_ECR_URI }}/todo-backend:latest

             # Create .env file
            sudo echo "MONGO_URI=${{ secrets.MONGO_URI }}" > .env

            # Run the new container with environment variables
            sudo docker run -d -p 5000:5000 \
              --env-file .env \
              --name todo-backend ${{ secrets.AWS_ECR_URI }}/todo-backend:latest
